[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []

[licenses]
allow = [
  "MIT",
  "Unicode-3.0",
  "BSD-3-Clause", # pipewire -> libspa -> bindgen
  "Apache-2.0", # pipewire -> libspa -> bindgen -> clang-sys
  "ISC", # pipewire -> libspa -> bindgen -> clang-sys -> libloading
  "Apache-2.0 WITH LLVM-exception", # cfg-expr
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = [
    "cfg-expr 0.15.8", # pipewire
]
